name: CD (Delivery)
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: The PR Agent
        uses: The-PR-Agent/pr-agent@v0.42.0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: subdir/go.sum